### ISSUE TITLE
feature request : launcher can do basic calculations

### ISSUE THREAD

**Issue by ywmaa** [ruditimmermans/launcher-modular#2]

**Comment by ruditimmermans** [comment]
Could you give me more info what you mean with calculations ?

**Comment by ywmaa** [comment]
if you used pop os launcher before that is what I mean, if I insert numebrs in the launcher (search bar) and use symbols like +,-,*,/ it will work like a calculator and show the result of the calculation.

**Comment by ruditimmermans** [comment]
Ok now i understand thanks!
