### ISSUE TITLE
feature request : search files

### ISSUE THREAD

**Issue by ywmaa** [ruditimmermans/launcher-modular#3]
maybe a keyword to hint for the launcher could help
something like 

file filename

**Comment by ruditimmermans** [comment]
You can always make a PR as i dont use Ubuntu Touch anymore....

**Comment by ruditimmermans** [comment]
I'm back on track only my developer device is broke so i need to search for a new one then i wil start working again on LM launcher, i was for some time away as i was waiting for a Waydroid fix that's why i was not able for some time to use UT.

**Comment by ywmaa** [comment]
awesome :smile:

**Comment by ruditimmermans** [comment]
I have been look into this but it would be not easy to do, i personly dont need this so i will not build it in, mebay someone who also one have it could make a PR to build it in....
